name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - uses: actions/checkout@v3

    - name: dotnet run
      run: dotnet run -c Release --project GdqScheduleToIcal.csproj -u https://gamesdonequick.com/schedule/41 -o agdq2023.ical

    - name: dotnet run
      run: dotnet run -c Release --project GdqScheduleToIcal.csproj -u https://gamesdonequick.com/schedule/42 -o ff2023.ical

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Schedule update"
